import type { Account, AIAction, CompetitorAlert, PipelineRisk, WebSignal } from './types'

const notionSignals: WebSignal[] = [
  {
    id: 's1',
    type: 'hiring_spike',
    title: '14 enterprise sales roles posted in 72 hours',
    evidence: 'Bright Data scraped 14 new Greenhouse listings for Enterprise AE, Sales Engineer, and RevOps roles — 3.2× above Notion\'s 90-day hiring baseline.',
    source: 'Bright Data Web Scraper',
    sourceUrl: 'https://boards.greenhouse.io/notion',
    confidence: 0.94,
    strength: 92,
    detectedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    impact: '+28 intent points',
  },
  {
    id: 's2',
    type: 'product_launch',
    title: 'New AI Workspace landing page detected',
    evidence: 'Web Scraper diff shows new /ai-workspace route with enterprise positioning, SOC2 badges, and "Contact Sales" CTA — not indexed 48h ago.',
    source: 'Bright Data Web Scraper',
    sourceUrl: 'https://notion.so/product/ai-workspace',
    confidence: 0.91,
    strength: 88,
    detectedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    impact: '+22 intent points',
  },
  {
    id: 's3',
    type: 'competitor_mention',
    title: 'Competitor cited in Notion blog post',
    evidence: 'SERP API surfaced new blog: "Why teams are switching from Coda" — mentions workflow automation gap your product solves.',
    source: 'Bright Data SERP API',
    sourceUrl: 'https://notion.so/blog/enterprise-workflows',
    confidence: 0.87,
    strength: 76,
    detectedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    impact: '+15 intent points',
  },
  {
    id: 's4',
    type: 'funding',
    title: 'Activity spike across news + social channels',
    evidence: 'Web Unlocker aggregated 23 articles referencing Notion enterprise expansion and AI monetization — 4.1× normal volume this week.',
    source: 'Bright Data Web Unlocker',
    sourceUrl: 'https://techcrunch.com/notion-enterprise',
    confidence: 0.89,
    strength: 81,
    detectedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    impact: '+18 intent points',
  },
]

export const accounts: Account[] = [
  {
    id: 'notion',
    name: 'Notion',
    domain: 'notion.so',
    industry: 'Productivity SaaS',
    employees: '500–1,000',
    intentScore: 94,
    previousScore: 41,
    status: 'hot',
    owner: 'Sarah Chen',
    lastTouch: '47 days ago',
    signals: notionSignals,
    decisionMakers: [
      { id: 'd1', name: 'Ivan Zhao', title: 'CEO & Co-founder', role: 'Economic buyer', hook: 'Recently quoted on enterprise AI strategy in Forbes — angle on workspace intelligence.' },
      { id: 'd2', name: 'Akshay Kothari', title: 'COO', role: 'Champion', hook: 'Led last vendor evaluation for sales tooling — prioritize ROI on rep productivity.' },
      { id: 'd3', name: 'Mia Torres', title: 'VP Revenue Operations', role: 'Technical evaluator', hook: 'Posted about RevOps stack consolidation on LinkedIn 6 days ago.' },
    ],
    outreachAngle: 'Lead with their enterprise sales hiring surge + new AI workspace page — position Revradar as the live web intelligence layer their RevOps team is missing before Q3 pipeline review.',
    aiReasoning: 'Notion crossed from dormant (41) to hot (94) in 72 hours. Four independent Bright Data signals converged: hiring velocity, product surface change, competitor narrative shift, and news volume spike. This pattern historically correlates with 68% meeting-book rate within 14 days for similar accounts.',
    recommendedAction: 'Assign to Sarah Chen · Draft enterprise outreach to Mia Torres · Create Salesforce task with signal evidence',
  },
  {
    id: 'linear',
    name: 'Linear',
    domain: 'linear.app',
    industry: 'Dev Tools',
    employees: '100–250',
    intentScore: 78,
    previousScore: 52,
    status: 'warming',
    owner: 'James Park',
    lastTouch: '31 days ago',
    signals: [
      {
        id: 'l1', type: 'hiring_spike', title: '8 GTM roles opened this week',
        evidence: 'Scraper detected 8 new roles across Sales, CS, and Partnerships — 2.1× baseline.',
        source: 'Bright Data Web Scraper', sourceUrl: 'https://linear.app/careers',
        confidence: 0.88, strength: 79, detectedAt: new Date(Date.now() - 6 * 3600000).toISOString(), impact: '+18 pts',
      },
    ],
    decisionMakers: [
      { id: 'ld1', name: 'Karri Saarinen', title: 'CEO', role: 'Economic buyer', hook: 'Publicly discussing PLG to enterprise motion transition.' },
    ],
    outreachAngle: 'Reference their GTM hiring wave and PLG-to-enterprise shift — offer signal-based account prioritization.',
    aiReasoning: 'Linear showing early warming signals. Hiring spike + pricing page update suggest enterprise push.',
    recommendedAction: 'Monitor for 48h · Prep outreach draft for VP Sales',
  },
  {
    id: 'retool',
    name: 'Retool',
    domain: 'retool.com',
    industry: 'Internal Tools',
    employees: '250–500',
    intentScore: 71,
    previousScore: 38,
    status: 'warming',
    owner: 'Unassigned',
    lastTouch: '62 days ago',
    signals: [
      {
        id: 'r1', type: 'pricing_change', title: 'Enterprise tier pricing restructured',
        evidence: 'Web Scraper diff on /pricing — new "Platform" tier with custom SSO and audit logs.',
        source: 'Bright Data Web Scraper', sourceUrl: 'https://retool.com/pricing',
        confidence: 0.92, strength: 85, detectedAt: new Date(Date.now() - 18 * 3600000).toISOString(), impact: '+24 pts',
      },
    ],
    decisionMakers: [],
    outreachAngle: 'Congratulate on enterprise tier launch — connect to revenue intelligence for their new sales motion.',
    aiReasoning: 'Pricing page change is a strong buying signal for enterprise expansion.',
    recommendedAction: 'Assign AE · Queue intro email',
  },
  {
    id: 'figma',
    name: 'Figma',
    domain: 'figma.com',
    industry: 'Design SaaS',
    employees: '1,000+',
    intentScore: 65,
    previousScore: 58,
    status: 'warming',
    owner: 'Sarah Chen',
    lastTouch: '22 days ago',
    signals: [],
    decisionMakers: [],
    outreachAngle: 'Monitor competitor mentions in design tooling space.',
    aiReasoning: 'Moderate intent uplift from leadership content activity.',
    recommendedAction: 'Add to watchlist',
  },
  {
    id: 'workstream',
    name: 'Workstream',
    domain: 'workstream.us',
    industry: 'HR Tech',
    employees: '100–250',
    intentScore: 91,
    previousScore: 34,
    status: 'hot',
    owner: 'Sarah Chen',
    lastTouch: '84 days ago',
    signals: [
      {
        id: 'w1', type: 'funding', title: '$48M Series B expansion surfaced',
        evidence: 'SERP API found fresh funding coverage with explicit enterprise sales hiring language and restaurant/franchise market expansion.',
        source: 'Bright Data SERP API', sourceUrl: 'https://techcrunch.com',
        confidence: 0.95, strength: 93, detectedAt: new Date(Date.now() - 2 * 3600000).toISOString(), impact: '+24 pts',
      },
      {
        id: 'w2', type: 'hiring_spike', title: '8 sales roles posted in 10 days',
        evidence: 'Web Scraper collected new Greenhouse roles for Enterprise AE, SDR Manager, RevOps, and Sales Enablement.',
        source: 'Bright Data Web Scraper', sourceUrl: 'https://boards.greenhouse.io/workstream',
        confidence: 0.91, strength: 89, detectedAt: new Date(Date.now() - 5 * 3600000).toISOString(), impact: '+18 pts',
      },
      {
        id: 'w3', type: 'review_activity', title: 'G2 reviews mention competitor switching',
        evidence: 'Web Unlocker extracted review snippets where multi-location operators compare Workstream to legacy hiring tools.',
        source: 'Bright Data Web Unlocker', sourceUrl: 'https://g2.com',
        confidence: 0.84, strength: 77, detectedAt: new Date(Date.now() - 11 * 3600000).toISOString(), impact: '+11 pts',
      },
    ],
    decisionMakers: [
      { id: 'wd1', name: 'Sarah Park', title: 'VP Sales', role: 'Champion', hook: 'Hiring SDRs and enterprise AEs; lead with ramp-time reduction.' },
      { id: 'wd2', name: 'Desmond Lim', title: 'CEO & Co-founder', role: 'Economic buyer', hook: 'Funding announcement makes GTM efficiency board-visible.' },
    ],
    outreachAngle: 'Tie the Series B and new SDR hiring plan to same-day signal-led account prioritization for new reps.',
    aiReasoning: 'Funding, hiring, review activity, and new RevOps ownership appeared within the same 14-day window. This is a high-confidence sales-stack evaluation moment.',
    recommendedAction: 'Send VP Sales email · Create HubSpot task · Slack Sarah Chen · Start 5-step sequence',
  },
  {
    id: 'parafin',
    name: 'Parafin',
    domain: 'parafin.com',
    industry: 'Fintech',
    employees: '50–100',
    intentScore: 83,
    previousScore: 49,
    status: 'hot',
    owner: 'Maya Rao',
    lastTouch: '19 days ago',
    signals: [
      {
        id: 'paf1', type: 'leadership_change', title: 'New CRO joined from Stripe',
        evidence: 'SERP and LinkedIn snippets show revenue leadership change followed by hiring for 10 AE roles.',
        source: 'Bright Data SERP API', sourceUrl: 'https://linkedin.com',
        confidence: 0.9, strength: 86, detectedAt: new Date(Date.now() - 3 * 3600000).toISOString(), impact: '+19 pts',
      },
      {
        id: 'paf2', type: 'hiring_spike', title: 'AE hiring burst in San Francisco',
        evidence: 'Web Scraper detected Account Executive, Sales Engineer, and Partner Sales roles across Greenhouse.',
        source: 'Bright Data Web Scraper', sourceUrl: 'https://boards.greenhouse.io/parafin',
        confidence: 0.92, strength: 88, detectedAt: new Date(Date.now() - 7 * 3600000).toISOString(), impact: '+16 pts',
      },
    ],
    decisionMakers: [
      { id: 'pd1', name: 'Rohit Arora', title: 'CRO', role: 'Champion', hook: 'New CROs often re-evaluate outbound stack in first 45 days.' },
      { id: 'pd2', name: 'Jessica Wu', title: 'CEO', role: 'Economic buyer', hook: '10 new AEs need pipeline quality quickly.' },
    ],
    outreachAngle: 'Position as the live account-prioritization layer for a new CRO scaling AE headcount.',
    aiReasoning: 'Leadership change plus AE hiring creates a predictable vendor review window. Signal density suggests outreach should happen this week.',
    recommendedAction: 'Assign Maya Rao · Draft CRO outreach · Push score to Salesforce · Create Slack alert',
  },
  {
    id: 'rootly',
    name: 'Rootly',
    domain: 'rootly.com',
    industry: 'DevOps SaaS',
    employees: '25–75',
    intentScore: 76,
    previousScore: 44,
    status: 'warming',
    owner: 'James Park',
    lastTouch: '53 days ago',
    signals: [
      {
        id: 'roo1', type: 'competitor_mention', title: 'Dark-funnel incident tooling threads',
        evidence: 'Web Unlocker captured Reddit and forum conversations comparing PagerDuty alternatives and mentioning Rootly.',
        source: 'Bright Data Web Unlocker', sourceUrl: 'https://reddit.com',
        confidence: 0.82, strength: 74, detectedAt: new Date(Date.now() - 4 * 3600000).toISOString(), impact: '+14 pts',
      },
      {
        id: 'roo2', type: 'hiring_spike', title: 'First outbound sales roles detected',
        evidence: 'Web Scraper found new AE and Sales Engineer roles that were not present in the previous crawl.',
        source: 'Bright Data Web Scraper', sourceUrl: 'https://jobs.lever.co/rootly',
        confidence: 0.85, strength: 78, detectedAt: new Date(Date.now() - 9 * 3600000).toISOString(), impact: '+13 pts',
      },
    ],
    decisionMakers: [
      { id: 'rd1', name: 'JJ Zhang', title: 'CEO', role: 'Champion', hook: 'PLG-to-sales shift makes signal timing a strategic advantage.' },
    ],
    outreachAngle: 'Lead with category research happening before vendor-form intent can see it.',
    aiReasoning: 'Dark-funnel competitor discussion plus first sales hires means the account is building sales capacity while buyers are already researching.',
    recommendedAction: 'Monitor 24h · Queue founder-led note · Add community-signal tag',
  },
  {
    id: 'scribe',
    name: 'Scribe',
    domain: 'scribehow.com',
    industry: 'Workflow SaaS',
    employees: '75–150',
    intentScore: 69,
    previousScore: 37,
    status: 'warming',
    owner: 'Unassigned',
    lastTouch: 'Never',
    signals: [
      {
        id: 'scr1', type: 'review_activity', title: 'Workflow documentation reviews spiked',
        evidence: 'Web Unlocker found new G2 review language about switching from manual walkthroughs and Loom-style documentation.',
        source: 'Bright Data Web Unlocker', sourceUrl: 'https://g2.com',
        confidence: 0.87, strength: 76, detectedAt: new Date(Date.now() - 8 * 3600000).toISOString(), impact: '+15 pts',
      },
      {
        id: 'scr2', type: 'hiring_spike', title: 'SDR manager role opened in SF',
        evidence: 'Web Scraper identified a new SDR Manager posting with outbound process ownership.',
        source: 'Bright Data Web Scraper', sourceUrl: 'https://boards.greenhouse.io/scribe',
        confidence: 0.8, strength: 71, detectedAt: new Date(Date.now() - 13 * 3600000).toISOString(), impact: '+12 pts',
      },
    ],
    decisionMakers: [
      { id: 'sd1', name: 'Jennifer Smith', title: 'CEO', role: 'Economic buyer', hook: 'Review momentum and SDR hiring suggest outbound motion is being professionalized.' },
    ],
    outreachAngle: 'Frame CaliSignal as the automation layer for turning category momentum into targeted outbound.',
    aiReasoning: 'Review language and new SDR leadership signal a move from founder-led growth to repeatable sales.',
    recommendedAction: 'Assign owner · Generate 3-touch email sequence · Add to HubSpot watchlist',
  },
]

export const competitorAlerts: CompetitorAlert[] = [
  {
    id: 'c1', competitor: 'Clay', type: 'pricing',
    title: 'Enterprise tier price increase (+18%)',
    summary: 'Web Scraper detected updated pricing table — Enterprise moved from $720/mo to $849/mo. Annual billing now default.',
    detectedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    severity: 'high', source: 'Bright Data Web Scraper',
  },
  {
    id: 'c2', competitor: 'Apollo.io', type: 'landing_page',
    title: 'New "AI SDR" landing page launched',
    summary: 'New /ai-sdr route with demo video, case studies, and aggressive "Replace your SDR team" messaging.',
    detectedAt: new Date(Date.now() - 9 * 3600000).toISOString(),
    severity: 'medium', source: 'Bright Data Web Scraper',
  },
  {
    id: 'c3', competitor: 'ZoomInfo', type: 'hiring',
    title: '23 sales roles posted in 5 days',
    summary: 'Hiring velocity 2.8× baseline across AE, SDR, and Sales Engineering — suggests aggressive Q3 push.',
    detectedAt: new Date(Date.now() - 14 * 3600000).toISOString(),
    severity: 'medium', source: 'Bright Data Web Scraper',
  },
  {
    id: 'c4', competitor: '6sense', type: 'messaging',
    title: 'Homepage hero copy pivot detected',
    summary: 'Messaging shifted from "ABM platform" to "Revenue AI OS" — positioning change may indicate market response.',
    detectedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    severity: 'low', source: 'Bright Data Web Scraper',
  },
  {
    id: 'c5', competitor: 'Common Room', type: 'product',
    title: 'Product Hunt launch: Signal Studio',
    summary: 'New feature announced for community-sourced buying signals — direct overlap with your positioning.',
    detectedAt: new Date(Date.now() - 36 * 3600000).toISOString(),
    severity: 'high', source: 'Bright Data SERP API',
  },
]

export const aiActions: AIAction[] = [
  {
    id: 'a1', accountId: 'notion', accountName: 'Notion', type: 'email_draft',
    title: 'Enterprise outreach to Mia Torres, VP RevOps',
    preview: 'Mia — noticed Notion posted 14 enterprise sales roles this week and launched a new AI Workspace page...',
    fullContent: `Subject: Notion's enterprise push + a thought on signal-driven pipeline

Hi Mia,

I noticed Notion posted 14 enterprise sales roles in the last 72 hours and launched a new AI Workspace landing page — clear signals you're scaling the enterprise motion.

Teams in similar expansion phases often struggle with knowing which dormant accounts to prioritize before QBR. We built Revradar to turn live web signals (hiring, product launches, pricing changes) into ranked GTM actions — powered by Bright Data's live web intelligence.

Worth 15 minutes to see how RevOps teams are using this to reactivate pipeline without adding SDR headcount?

Best,
Sarah`,
    confidence: 0.91, status: 'pending',
    targetEmail: 'mia@notion-demo.com',
    owner: 'Sarah Chen',
    moat: ['14 hiring posts', 'AI Workspace page diff', 'Coda competitor mention', '47-day dormant CRM gap'],
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: 'a2', accountId: 'notion', accountName: 'Notion', type: 'crm_update',
    title: 'Update Salesforce: Intent score 41 → 94',
    preview: 'Set Account Intent Score to 94 · Add 4 signal tags · Move stage to "Re-engage"',
    fullContent: 'Account: Notion\nIntent Score: 94 (was 41)\nStage: Re-engage\nTags: hiring_spike, product_launch, competitor_mention, news_spike\nOwner: Sarah Chen\nNext Step: Send enterprise outreach',
    confidence: 0.96, status: 'pending',
    owner: 'Sarah Chen',
    moat: ['Salesforce stale stage', '4 verified Bright Data tags', 'Intent delta 41 to 94'],
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: 'a3', accountId: 'retool', accountName: 'Retool', type: 'owner_assignment',
    title: 'Assign Retool to James Park (Enterprise AE)',
    preview: 'James owns 3 similar internal-tools accounts · 2 closed-won in last 6 months',
    fullContent: 'Recommended owner: James Park\nReason: Vertical expertise in internal tools + existing relationship with Retool engineering leadership via conference intro.',
    confidence: 0.84, status: 'pending',
    owner: 'James Park',
    moat: ['Closed-won similarity match', 'Internal tools vertical expertise', 'Conference relationship memory'],
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'a4', accountId: 'linear', accountName: 'Linear', type: 'slack_alert',
    title: 'Slack alert: Linear warming up',
    preview: '#gtm-signals · Linear intent +26 pts · 8 GTM roles detected',
    fullContent: '🔥 Linear is warming up\nIntent: 52 → 78 (+26)\nSignal: 8 GTM roles posted this week\nOwner: James Park\n→ View in Revradar',
    confidence: 0.88, status: 'pending',
    owner: 'James Park',
    moat: ['8 GTM roles', 'Owner already mapped', 'Slack channel #gtm-signals active'],
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 'a5', accountId: 'workstream', accountName: 'Workstream', type: 'sequence_start',
    title: 'Start 5-step multi-channel sequence for VP Sales',
    preview: 'Email + LinkedIn + call opener tied to Series B, 8 sales hires, and RevOps intent-data wording.',
    fullContent: 'Sequence: 1) Funding/hiring email to VP Sales 2) LinkedIn voice note 3) RevOps proof point 4) Case-study bump 5) Breakup with hiring benchmark.\n\nPersonalization moat: Series B press language, Greenhouse job descriptions, review-site pain, CRM last-touch gap.',
    confidence: 0.9, status: 'pending',
    targetEmail: 'sarah@workstream-demo.com',
    owner: 'Sarah Chen',
    moat: ['Series B expansion', '8 sales roles', 'RevOps JD mentions intent data', 'G2 competitor switching'],
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'a6', accountId: 'parafin', accountName: 'Parafin', type: 'enrichment_refresh',
    title: 'Refresh live enrichment before CRO outreach',
    preview: 'Re-scan LinkedIn/jobs/SERP, update committee, and regenerate email if a new AE role appears.',
    fullContent: 'Agent plan:\n- Pull fresh SERP snippets for Parafin CRO and Series B\n- Re-scrape Greenhouse roles\n- Check competitor and partner-page mentions\n- Regenerate CRO email and Slack AE alert\n- Write new evidence to CRM timeline',
    confidence: 0.87, status: 'pending',
    owner: 'Maya Rao',
    moat: ['New CRO window', 'Series B budget timing', 'AE hiring velocity', 'Stripe alumni angle'],
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
]

export const pipelineRisks: PipelineRisk[] = [
  { id: 'p1', accountName: 'Databricks', risk: 'Competitor pricing undercut detected', score: 34, trend: 'down' },
  { id: 'p2', accountName: 'Stripe', risk: 'No web signals in 45 days — going cold', score: 28, trend: 'down' },
  { id: 'p3', accountName: 'Airtable', risk: 'Leadership departure signal', score: 41, trend: 'down' },
]

export const signalVolumeData = [
  { day: 'Mon', signals: 142, warm: 8 },
  { day: 'Tue', signals: 168, warm: 11 },
  { day: 'Wed', signals: 195, warm: 9 },
  { day: 'Thu', signals: 221, warm: 14 },
  { day: 'Fri', signals: 287, warm: 12 },
  { day: 'Sat', signals: 134, warm: 6 },
  { day: 'Sun', signals: 156, warm: 7 },
]

export const dashboardStats = {
  dormantToWarm: 12,
  signalsToday: 287,
  actionsPending: 4,
  avgIntentLift: 34,
  competitorMoves: 5,
  pipelineAtRisk: 3,
}

export function getAccount(id: string): Account | undefined {
  return accounts.find(a => a.id === id)
}

export const brightDataIntegrations = [
  { name: 'Web Scraper API', status: 'live' as const, signals: 1842, latency: '1.2s' },
  { name: 'SERP API', status: 'live' as const, signals: 624, latency: '0.8s' },
  { name: 'Web Unlocker', status: 'live' as const, signals: 412, latency: '2.1s' },
  { name: 'Bright Data MCP', status: 'live' as const, signals: 156, latency: '0.4s' },
]
